; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:seeed_wio_terminal]
platform = atmelsam
board = seeed_wio_terminal
framework = arduino
lib_deps =
    seeed-studio/Seeed_Arduino_LCD@^2.0.3
monitor_speed = 115200
build_flags =
    -DUSER_SETUP_LOADED=1
    -DILI9341_DRIVER=1
    -DTFT_SPI_PORT=LCD_SPI
    -DTFT_CS=LCD_SS_PIN
    -DTFT_DC=LCD_DC
    -DTFT_BL=LCD_BACKLIGHT
    -DTFT_BACKLIGHT_ON=HIGH
    -DTFT_RST=LCD_RESET
    -DLOAD_GLCD=1
    -DLOAD_FONT2=1
    -DLOAD_FONT4=1
    -DLOAD_FONT6=1
    -DLOAD_FONT7=1
    -DLOAD_FONT8=1
    -DLOAD_GFXFF=1
    -DSPI_FREQUENCY=50000000
    -DSPI_READ_FREQUENCY=20000000
